### PR TITLE
Ported Over View Frustum Culling.

### PR DESCRIPTION
**Pull request by joncatanio**
Take a look at this, I tried to make ViewFrustum.h/.cpp as clean as possible so when we do end up doing a hierarchy it would be easy to have a bunch of ViewFrustum objects. I currently have a single ViewFrustum object in the GameManager, I couldn't really think of a more logical way to do it, let me know if you have any better ones.

Also I included the viewport in the bottom left corner of the screen and added a preprocessor definition around it (also updated cmake to handle this). If you don't want `DEBUG` set then edit the CMakeLists.txt to not include the debug definition.

### CODE REVIEW

**Review by rgarmsen2295 — APPROVED** [review]
Looks good, I see what you mean with tabs/spaces, I believe VS defaulted it to 4 space tabs but I could be wrong.  I'm guessing you have vim set to 3 spaces? We'll probably just set to that after 50% for all files, I tried to fix some of em earlier, but that led to merge conflict bonanza :P

**Comment by rgarmsen2295** [comment]
Also, for the VFC hierarchy, I don't believe that would actually entail multiple VFCs (it's not the interior portal stuff Zoe mentioned).  Rather, at that point, you need to have a hierarchy/tree of BoundingBoxes around larger -> smaller sets of objects.  This allows you to not have to check every individual BoundingBox against the VF planes.

Here's an example: http://images.slideplayer.com/23/6850485/slides/slide_10.jpg (except we have boxes).

Only thing I'm not sure of is how exactly to integrate with the Octree since that's what we'll (I'll) be using here for now. I guess something like this visually http://images.slideplayer.com/14/4427346/slides/slide_15.jpg

**Comment by rgarmsen2295** [comment]
Also, now that I'm a bit more awake, does the VF even need to be a 'global' (aka in the singleton)? It seems to be basically recreated every loop in the main render/draw call, maybe just leave it as a local in that function?

**Comment by nurgan** [comment]
Look good.
For the global VF, I think thats good, its recalculated every update cycle, but it's always one VF we don't allocate newly.
For the spaces/tabs, we should just auto format all files to whatever we want and then all set up our editors identical (as normal people would do first xD).

**Review by nurgan — APPROVED** [review]

**Comment by rgarmsen2295** [comment]
Fair enough, I guess it is fairly heavy.

And yeah, hahah, we should do that

**Pull request merged**
